import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
import { NextPage } from "next";

interface Home {
  id: string;
  title: string;
  description: string;
  image: string;
}

interface HomeProps {
  data: Home[];
}

const Home: NextPage<HomeProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => {
          return (
            <Link key={ev.id} href={`events/${ev.id}`}>
              <Image width={300} height={300} alt={ev.title} src={ev.image} />
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </Link>
          );
        })}
      </main>

      <footer></footer>
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
