import Head from "next/head";

import { NextPage } from "next";
import { HomePage, HomeProps } from "@/src/components/home/home-page";

const Home: NextPage<HomeProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
};

export default Home;

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");
  console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
